version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[p]hp-fpm: master'"]
      interval: 1s
      retries: 80
      start_period: 1s
      timeout: 1s
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: "exit 0"
      interval: 1s
      retries: 10
      start_period: 1s
      timeout: 1s

networks:
  inception:
    name: inception

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: $WORDPRESS_PATH
      o: bind

  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: $MARIA_DB_PATH
      o: bind
